#!/bin/bash

# Paths
add_tmppath "$HOME/.local/bin"
add_tmppath "$HOME/.cabal/bin"

add_tmppath "/usr/local/sbin"
add_tmppath "/usr/local/bin"
add_tmppath "/usr/sbin"
add_tmppath "/usr/bin"
add_tmppath "/sbin"
add_tmppath "/bin"

add_tmppath "/usr/local/lib"
add_tmppath "/usr/lib"
add_tmppath "/lib"

# Editor
export EDITOR="vim"

# Colors
LS_COLORS=""

rule () {
  tg="$1"
  if [[ "$LS_COLORS" == "" ]]; then
    export LS_COLORS="$tg"
  else
    export LS_COLORS="$LS_COLORS:$tg"
  fi
}

rule "di=32"          DIRECTORY
rule "fi=0"           FILES
rule "ln=0"           LINKS
rule "ex=1;34"        EXECUTABLE
rule "*akefile=1;35"
rule "*pdf=1;91"
