# This file is sourced at any zsh interactive shell
debug "sourcing .zshrc"
indent

export KEYBOARD='QWERTY'

# Path to your oh-my-zsh installation.
# ZSH=$HOME/.oh-my-zsh

# ZSH_THEME="agnoster"

plugins=()
# plugins=("zsh-autosuggestions" "zsh-syntax-highlighting")

CASE_SENSITIVE="false"

export CC=$(which cc)

# No autocorrection
unsetopt correct_all

# safe_source $ZSH/oh-my-zsh.sh
# safe_source ~/.aliases/aliases

precmd() {
}

autoload bashcompinit
bashcompinit

make_completion() {
  local bin=$1

  if [[ "$(which ${bin})" == "${bin} not found" ]]
  then
    return 0
  fi

  local loc="$(which ${bin})"
  source <(${bin} --bash-completion-script ${loc})
}

export PATH=/home/nick/anaconda3/bin:$PATH

# l
ls -ltr

outdent

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
